# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ew5TLIA8v1MPa8RrnotmKDHP-_Zjgbl6
"""

from flask import Flask, request, jsonify
import numpy as np
import pandas as pd

# Initialize the Flask app
app = Flask(__name__)

# In-memory trained model (Use the same model as above)
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)  # Train the model in this session

# Sample knowledge graph recommendations
def get_recommendations(prediction):
    if prediction == 1:
        return ["Employee engagement program", "Career development workshop"]
    else:
        return ["Exit interview", "Performance review follow-up"]

# Define the API endpoint
@app.route('/predict', methods=['POST'])
def predict():
    data = request.get_json()
    features = np.array([
        data['age'], data['length_of_service'],
        data['department_name'], data['job_title'],
        data['gender_full'], data['BUSINESS_UNIT']
    ]).reshape(1, -1)

    prediction = model.predict(features)[0]
    recommendations = get_recommendations(prediction)

    return jsonify({
        'prediction': 'Active' if prediction == 1 else 'Terminated',
        'recommendations': recommendations
    })

if __name__ == '__main__':
    app.run(debug=True)